### ISSUE TITLE
Trigger deployment only on master branch

### ISSUE THREAD

**Issue by mphasize** [surge-sh/example-travisci#1]
Any idea how to run the `after_success` surge command only on updates in `master`? With the example given in the README, surge deployment is triggered on every (successfully tested) commit in every branch, which is not ideal. Thanks!

**Comment by stevenmathews** [comment]
Seems like [script deployment](http://docs.travis-ci.com/user/deployment/script/) is the way to go as it gives access to the 'on' option for deploy.

**Comment by mathiasrw** [comment]
You can use `$TRAVIS_BRANCH` - so instead of calling surge like

```
surge -Project ...
```

you prepend a check so it ends up like 

```
[[ $TRAVIS_BRANCH == 'master' ]] && surge -Project ....
```
